# Generated by Django 5.0.6 on 2024-07-09 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_change_customer', 'Can change customer'), ('can_delete_customer', 'Can delete customer'))},
        ),
        migrations.AlterField(
            model_name='customer',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 18, 11, 20, 904104)),
        ),
    ]
